package com.blackolive.app.service.brandPage;

import java.sql.SQLException;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.blackolive.app.domain.brandPage.BrandPageDTO;
import com.blackolive.app.mapper.brandPage.BrandPageMapper;

import lombok.extern.log4j.Log4j;

@Service
@Log4j
public class BrandPageServiceImpl implements BrandPageService  {

	@Autowired
	private BrandPageMapper brandpageMapper;

	@Override
	public BrandPageDTO getBrands(String brandId) throws ClassNotFoundException, SQLException {
		return brandpageMapper.getBrands(brandId);
	}

	@Override
	public List<BrandPageDTO> getSortBrands(String brandId, String sort, String dispcatno)
			throws ClassNotFoundException, SQLException {
		return brandpageMapper.getSortBrands(brandId, dispcatno, sort);
	}

	@Override
	public String createBrandPageHtml(String brandId, String sort, String dispcatno 
			)throws Exception {
 
		
		log.info("> BRAND PAGE HTML......");
		
		StringBuilder html = new StringBuilder();
	    List<BrandPageDTO> brandPageList = getSortBrands(brandId, sort, dispcatno);
	    
        System.out.println(" brandPageList.size(): " + brandPageList );
       // BrandPageDTO product = new BrandPageDTO();
        
/*
            for (BrandPageDTO product : brandPageList) {
                html.append("<li data-goods-idx=\"" + product.getProductDisplayId() + "\">\r\n"););
                html.append("    <div class=\"prod\">\r\n"););
                html.append("        <a href=\"#\" name=\"" + product.getProductDisplayName() + "\" class=\"thumb goodsList\" data-ref-goodsNo=\"" + product.getGoodsNo() + "\" data-ref-dispCatNo=\"" + product.getCategoryLargeId() + "\" data-ref-itemNo=\"001\">\r\n"););
                html.append("            <img src=\"" + product.getProductDisplaySrc() + "\" alt=\"" + product.getGoodsName() + "\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n"););
                html.append("            <span class=\"flag-badge best\">" + product.getBadge() + "</span>\r\n"););
                html.append("        </a>\r\n"););
                html.append("");
                html.append("");
                html.append("");
                html.append("            <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"" + product.getProductDisplayName() + "\" data-item-no=\"001\">\r\n"););
                html.append("                <span>장바구니</span>\r\n"););
                html.append("            </button>\r\n"););
                html.append("        </div>\r\n"););
                html.append("    </li>\r\n"););
            }

            return html.toString();
        }

        ///
        /*
        html.append("<input type=\"hidden\" id=\"strList\" name=\"strList\" value=\"\"/>\r\n");
 html.append( "<input type=\"hidden\" id=\"lgcGoodsList\" name=\"lgcGoodsList1\" value=\"\"/>\r\n");
 html.append( "<input type=\"hidden\" id=\"idx\" name=\"idx\" value=\"1\"/>\r\n");
 html.append( "<input type=\"hidden\" id=\"totCntFmt\" name=\"totCntFmt\" value=\"14\"/>\r\n");
 html.append( "<input type=\"hidden\" id=\"goodsTrackingCd\" name=\"goodsTrackingCd\" value=\"\"/>\r\n");
 html.append( "<ul class=\"prod-list goodsProd\">\r\n");
 html.append( "    <li data-goods-idx=\"1\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000192385&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=1\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000192385\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0019/A00000019238514ko.jpg?l=ko\" alt=\"[2023어워즈] 구달 청귤 비타C 잡티케어 세럼 50ml 어워즈 한정기획 (50ml+50ml리필)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "                <span class=\"flag-badge best\">베스트</span>\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000192385&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=1\" class=\"goodsList\" data-ref-goodsNo=\"A000000192385\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[2023어워즈] 구달 청귤 비타C 잡티케어 세럼 50ml 어워즈 한정기획 (50ml+50ml리필)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\"></span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            28,900<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.8</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.8점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000192385\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000192385\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"2\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162021&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=2\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000162021\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0016/A00000016202129ko.jpg?l=ko\" alt=\"[한정기획] 구달 청귤 비타C 잡티케어 크림 75ml 기획(+크림 10mlx2ea 증정)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "                <span class=\"flag-badge best\">베스트</span>\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162021&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=2\" class=\"goodsList\" data-ref-goodsNo=\"A000000162021\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[한정기획] 구달 청귤 비타C 잡티케어 크림 75ml 기획(+크림 10mlx2ea 증정)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">28,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            21,000<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000162021\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000162021\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"3\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165071&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=3\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000165071\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0016/A00000016507112ko.jpg?l=ko\" alt=\"[한정기획] 구달 맑은 어성초 진정 수분크림 75ml 기획(+세럼 20ml+화장솜 20매 증정)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165071&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=3\" class=\"goodsList\" data-ref-goodsNo=\"A000000165071\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[한정기획] 구달 맑은 어성초 진정 수분크림 75ml 기획(+세럼 20ml+화장솜 20매 증정)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">26,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            19,760<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000165071\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000165071\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"4\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000171548&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=4\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000171548\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0017/A00000017154812ko.jpg?l=ko\" alt=\"[한정기획] 구달 청귤 비타C 다크서클 아이크림 30ml 기획 (+15ml*2ea증정)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000171548&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=4\" class=\"goodsList\" data-ref-goodsNo=\"A000000171548\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[한정기획] 구달 청귤 비타C 다크서클 아이크림 30ml 기획 (+15ml*2ea증정)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">24,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            18,240<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.6</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.6점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000171548\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000171548\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "</ul>\r\n");
 html.append( "<ul class=\"prod-list goodsProd\">\r\n");
 html.append( "    <li data-goods-idx=\"5\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162323&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=5\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000162323\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0016/A00000016232331ko.jpg?l=ko\" alt=\"[한정기획] 구달 청귤 비타C 잡티케어 세럼 50ml+31ml 증정 기획\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162323&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=5\" class=\"goodsList\" data-ref-goodsNo=\"A000000162323\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[한정기획] 구달 청귤 비타C 잡티케어 세럼 50ml+31ml 증정 기획</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">43,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            28,900<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000162323\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000162323\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"6\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165118&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=6\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000165118\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0016/A00000016511813ko.jpg?l=ko\" alt=\"[한정기획] 구달 맑은 어성초 진정 에센스 150ml 기획 (+수분세럼 20ml+수분크림 10ml+화장솜 10매 증정)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000165118&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=6\" class=\"goodsList\" data-ref-goodsNo=\"A000000165118\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[한정기획] 구달 맑은 어성초 진정 에센스 150ml 기획 (+수분세럼 20ml+수분크림 10ml+화장솜 10매 증정)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">30,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            22,800<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000165118\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000165118\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"7\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162325&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=7\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000162325\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0016/A00000016232517ko.jpg?l=ko\" alt=\"[단독기획] 구달 청귤 비타C 잡티케어 세럼 30ml 기획 (+세럼 10ml +마스크팩 1매 증정)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000162325&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=7\" class=\"goodsList\" data-ref-goodsNo=\"A000000162325\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[단독기획] 구달 청귤 비타C 잡티케어 세럼 30ml 기획 (+세럼 10ml +마스크팩 1매 증정)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">28,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            22,400<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000162325\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000162325\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"8\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000183371&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=8\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000183371\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0018/A00000018337104ko.jpg?l=ko\" alt=\"[1+1기획] 구달 맑은 어성초 진정 수분 토너 300ml 기획(+300ml 리필)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000183371&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=8\" class=\"goodsList\" data-ref-goodsNo=\"A000000183371\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[1+1기획] 구달 맑은 어성초 진정 수분 토너 300ml 기획(+300ml 리필)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">30,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            24,000<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.8</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.8점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000183371\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000183371\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "</ul>\r\n");
 html.append( "<ul class=\"prod-list goodsProd\">\r\n");
 html.append( "    <li data-goods-idx=\"9\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000190108&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=9\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000190108\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0019/A00000019010811ko.jpg?l=ko\" alt=\"[재유PICK/단독기획]구달 흑당근 비타A 레티놀 탄력 앰플 30ml 기획 (+앰플 9ml*2ea)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000190108&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=9\" class=\"goodsList\" data-ref-goodsNo=\"A000000190108\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[재유PICK/단독기획]구달 흑당근 비타A 레티놀 탄력 앰플 30ml 기획 (+앰플 9ml*2ea)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">34,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            22,610<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.9</span>\r\n");
 html.append( "                        <span class=\"num\">(797)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.9점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(797)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000190108\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000190108\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"10\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000171546&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=10\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000171546\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0017/A00000017154601ko.jpg?l=ko\" alt=\"[단독기획] 구달 청귤 비타C 잡티 톤업크림 50ml 기획 (+톤업크림5ml+세럼5ml)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000171546&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=10\" class=\"goodsList\" data-ref-goodsNo=\"A000000171546\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[단독기획] 구달 청귤 비타C 잡티 톤업크림 50ml 기획 (+톤업크림5ml+세럼5ml)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">22,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            17,600<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.5</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.5점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000171546\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000171546\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"11\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000190110&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=11\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000190110\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0019/A00000019011010ko.jpg?l=ko\" alt=\"[단독기획]구달 흑당근 비타A 레티놀 탄력 크림 50ml 기획 (+크림 15ml*2ea)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000190110&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=11\" class=\"goodsList\" data-ref-goodsNo=\"A000000190110\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[단독기획]구달 흑당근 비타A 레티놀 탄력 크림 50ml 기획 (+크림 15ml*2ea)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">34,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            24,220<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.6</span>\r\n");
 html.append( "                        <span class=\"num\">(165)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.6점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(165)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000190110\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000190110\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"12\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000189125&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=12\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000189125\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0018/A00000018912511ko.jpg?l=ko\" alt=\"[NEW] 구달 흑당근 비타A 레티놀 탄력 크림 50ml\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000189125&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=12\" class=\"goodsList\" data-ref-goodsNo=\"A000000189125\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[NEW] 구달 흑당근 비타A 레티놀 탄력 크림 50ml</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">34,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            24,220<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(43)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(43)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000189125\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000189125\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "</ul>\r\n");
 html.append( "<ul class=\"prod-list goodsProd\">\r\n");
 html.append( "    <li data-goods-idx=\"13\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000164882&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=13\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000164882\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0016/A00000016488210ko.jpg?l=ko\" alt=\"[단독기획] 구달 맑은 어성초 진정 수분 세럼 50ml 기획(+토너 50ml+화장솜 10매 증정)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000164882&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=13\" class=\"goodsList\" data-ref-goodsNo=\"A000000164882\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[단독기획] 구달 맑은 어성초 진정 수분 세럼 50ml 기획(+토너 50ml+화장솜 10매 증정)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            24,000<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.8</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.8점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags blank\"></div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000164882\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000164882\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <li data-goods-idx=\"14\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000189124&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=14\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000189124\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"https://image.oliveyoung.co.kr/uploads/images/goods/400/10/0000/0018/A00000018912409ko.jpg?l=ko\" alt=\"[NEW] 구달 흑당근 비타A 레티놀 탄력 앰플 30ml\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000189124&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=14\" class=\"goodsList\" data-ref-goodsNo=\"A000000189124\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[NEW] 구달 흑당근 비타A 레티놀 탄력 앰플 30ml</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\">34,000원</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append( "                            22,610<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.7</span>\r\n");
 html.append( "                        <span class=\"num\">(46)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.7점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(46)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000189124\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000189124\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
 html.append( "    <div class=\"pageing\">\r\n");
 html.append( "        <strong title=\"현재 페이지\">1</strong>\r\n");
 html.append( "    </div>\r\n");
 html.append( "");
		*/
      
        try {
        	
        	 html.append("<input type=\"hidden\" id=\"strList\" name=\"strList\" value=\"\"/>\r\n");
        	 html.append( "<input type=\"hidden\" id=\"lgcGoodsList\" name=\"lgcGoodsList1\" value=\"\"/>\r\n");
        	 html.append( "<input type=\"hidden\" id=\"idx\" name=\"idx\" value=\"1\"/>\r\n");
        	 html.append( "<input type=\"hidden\" id=\"totCntFmt\" name=\"totCntFmt\" value=\"14\"/>\r\n");
        	 html.append( "<input type=\"hidden\" id=\"goodsTrackingCd\" name=\"goodsTrackingCd\" value=\"\"/>\r\n");
        	 
        	 
        for ( int i = 0; i < brandPageList.size(); i++) {
			BrandPageDTO product = brandPageList.get(i);
			
			System.out.println(">DDD"+brandPageList);
				
			  
		      if (i % 4 == 0) {
		    	   if( i != 0 )  html.append( "</ul>\r\n");
		           //  html.append("<div class=\"row\">");
		            System.out.println(">aaa");
		            
		            html.append( "<ul class=\"prod-list goodsProd\">\r\n");
		        }



 html.append( "    <li data-goods-idx=\"1\">\r\n");
 html.append( "        <div class=\"prod\">\r\n");
 html.append( "            <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000192385&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=1\" name=\"BrandA001436_PROD\" class=\"thumb goodsList\" data-ref-goodsNo=\"A000000192385\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                <img src=\"" + product.getProductDisplaySrc() + "\" alt=\"[2023어워즈] 구달 청귤 비타C 잡티케어 세럼 50ml 어워즈 한정기획 (50ml+50ml리필)\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n");
 html.append( "                <span class=\"flag-badge best\">베스트</span>\r\n");
 html.append( "            </a>\r\n");
 html.append( "            <div class=\"prod-info\">\r\n");
 html.append( "                <div class=\"prod-brand\">\r\n");
 html.append( "                    <strong class=\"exclusive\"></strong>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <a href=\"https://www.oliveyoung.co.kr/store/goods/getGoodsDetail.do?goodsNo=A000000192385&dispCatNo=9000002&trackingCd=BrandA001436_PROD&t_page=브랜드관&t_click=전체상품_상품상세&t_number=1\" class=\"goodsList\" data-ref-goodsNo=\"A000000192385\" data-ref-dispCatNo=\"9000002\" data-ref-itemNo=\"001\">\r\n");
 html.append( "                    <span class=\"prod-name double-line\">[2023어워즈] 구달 청귤 비타C 잡티케어 세럼 50ml 어워즈 한정기획 (50ml+50ml리필)</span>\r\n");
 html.append( "                </a>\r\n");
 html.append( "                <div class=\"price-info\">\r\n");
 html.append( "                    <div class=\"discount\">\r\n");
 html.append( "                        <span class=\"origin\"></span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"price\">\r\n");
 html.append( "                        <strong class=\"total\">\r\n");
 html.append("                            " + String.format("%,d", product.getAfterPrice()) + "<span class=\"won\">원</span>\r\n");
 html.append( "                        </strong>\r\n");
 html.append( "                        <span class=\"oneday\">오늘드림</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating\">\r\n");
 html.append( "                        <span class=\"point\">4.8</span>\r\n");
 html.append( "                        <span class=\"num\">(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                    <div class=\"rating_type\">\r\n");
 html.append( "                        <div class=\"rating_point star5\">\r\n");
 html.append( "                            <span class=\"oyblind\">별점 5점 만점에 4.8점</span>\r\n");
 html.append( "                        </div>\r\n");
 html.append( "                        <span>(999+)</span>\r\n");
 html.append( "                    </div>\r\n");
 html.append( "                </div>\r\n");
 html.append( "                <div class=\"flags\">\r\n");
 html.append( "                    <span class=\"flag sale\">세일</span>\r\n");
 html.append( "                    <span class=\"flag coupon\">쿠폰</span>\r\n");
 html.append( "                </div>\r\n");
 html.append( "            </div>\r\n");
 html.append( "            <div class=\"prod-func\">\r\n");
 html.append( "                <button type=\"button\" class=\"favorite\" data-ref-goodsNo=\"A000000192385\">\r\n");
 html.append( "                    <span>찜하기</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "                <button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"A000000192385\" data-item-no=\"001\">\r\n");
 html.append( "                    <span>장바구니</span>\r\n");
 html.append( "                </button>\r\n");
 html.append( "            </div>\r\n");
 html.append( "        </div>\r\n");
 html.append( "    </li>\r\n");
        		
        		
 /*	
		        html.append("<div class=\"prod\">");
		        html.append("<a href=\"#\" class=\"thumb goodsList\" data-ref-goodsno=\"" + product.getProductDisplayId() + "\">\r\n"););
		        html.append("<img src=\"" + product.getProductDisplaySrc() + "\" alt=\"" + product.getProductDisplayName() + "\" class=\"pic-thumb\" onerror=\"common.errorImg(this);\">\r\n"););
		        html.append("<span class=\"flag-badge best\">베스트</span>");
		        html.append("</a>");
		        html.append("<div class=\"prod-info\">");
		        html.append("<div class=\"prod-brand\"><strong class=\"exclusive\"></strong></div>");
		        html.append("<a href=\"#\" class=\"goodsList\" data-ref-goodsno=\"" + product.getProductDisplayId() + "\">\r\n"););
		        html.append("<span class=\"prod-name double-line\">" + product.getProductDisplayName() + "</span>\r\n"););
		        html.append("</a>");
		        html.append("</div>");
		        html.append("<div class=\"prod-func\">");
		        html.append("<button type=\"button\" class=\"favorite\" data-ref-goodsno=\"" + product.getProductDisplayId() + "\">\r\n"););
		        html.append("<span>찜하기</span>");
		        html.append("</button>");
		        html.append("<button type=\"button\" class=\"cart\" onclick=\"common.gf_regCart(this); return false;\" data-goods-no=\"" + product.getProductDisplayId() + "\" data-item-no=\"001\">\r\n"););
		        html.append("<span>장바구니</span>");
		        html.append("</button>");
		        html.append("</div>\r\n"););
		        html.append("</div>\r\n"););
*/
		      
		       //if ((i + 1) % 4 == 0 || (i + 1) == brandPageList.size()) {
		          //html.append("</div>");
		     //  }
		    }
        } catch (Exception e) {
            
            return "";
        }
        
		return html.toString();
	
	}
	



	@Override
	public List<BrandPageDTO> getsellProduct(String brandId, String categoryId)
			throws ClassNotFoundException, SQLException {
		return brandpageMapper.getsellProduct(brandId, categoryId);
	}

	@Override
	public List<BrandPageDTO> getReviews(String brandId) throws ClassNotFoundException, SQLException {
		return brandpageMapper.getReviews(brandId);
	}





}
